import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppThemeProvider from "@/common/AppThemeProvider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Recipe App",
    description: "Generated by Recipe App",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={{backgroundColor:"lightgray"}}>
                <AppThemeProvider>
                    {children}
                </AppThemeProvider>
            </body>
        </html>
    );
}
